### ISSUE TITLE
Allow user to search species in post to iNat

### ISSUE THREAD

**Issue by albullington** [inaturalist/SeekReactNative#105]
Add a new screen that allows users to search for species. Need to figure out how to filter these -- should users simply search by name? How does this work in different languages?
https://zpl.io/a7WvWGM

**Comment by kamerat** [comment]
Was this ever added to the app? I cannot seem to find it.
I'm looking for some type of search option to find spesific species. Closest thing is the "Nearby species" but this has no immediate search function as far as I see.
