### ISSUE TITLE
Allow users to select photo albums in photo chooser

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#107]
Just to make it a bit easier to find the photos in their library, if possible.

**Comment by albullington** [comment]
@abhasinat any particular design requests around this? Use the native picker in the header bar and maybe change the text that says "choose a photo" to let users know they can select albums instead?

**Comment by abhasinat** [comment]
I think the main UI change here would be to change "Choose a photo" to "Camera Roll" or whatever the default album is, with a "˅" or downward-point triangle icon next to it to indicate that the user can change it. Clicking it would open the native albums view on the device, and the user could select a different album to view images from. Does that work in React, @albullington?

**Comment by albullington** [comment]
I don't believe there's a way to access the native albums view. I can access photos from different albums within the app, which is why I thought a native picker might give users a way to filter results from those different albums. Also TBD on how well this works in RN.

**Comment by albullington** [comment]
Left a comment in a related issue [here](https://github.com/react-native-community/react-native-cameraroll/issues/41)

**Comment by albullington** [comment]
Added the `react-native-gallery-manager` library to be able to access album names from a user's device.
