### ISSUE TITLE
Improve behavior when Seek can't access photos

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#112]
This is on an iPhone XS running iOS 12.3.1. Probably not a common scenario, but it was noted in the forum. https://forum.inaturalist.org/t/seek-app-behaves-in-a-confusing-manner-when-access-to-photos-is-turned-off-iphone/4305

1. Don't allow Seek to access your photos.
2. Open camera and take a photo 
3. Image freezes and we see "Sorry, we weren't able to save your photo."
4. Model still works if you point the camera to other things, but image stays frozen, eg:

![image](https://user-images.githubusercontent.com/15896181/59947042-10e84580-9421-11e9-9eca-b6a76ad6cbf6.png)

Can we handle this situation by making it clear to the user that they need to change the photo permissions, and maybe close the camera?

**Comment by albullington** [comment]
Updated with this error screen, which encourages the user to go into their settings and change permissions: https://zpl.io/2EB4yJy
