### ISSUE TITLE
Allow users to mark and observation as incorrectly identified = "flag incorrect"

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#115]
There's an increasing request for users to be able to mark an ID in Seek as incorrect. Users want to be able to give feedback to Seek when they know the ID is incorrect.

This feature would only be available from the results screen **immediately after the user makes an observation to species**. This modal would be accessed from the navigation bar, where the notifications icon would be replaced with a flag icon.
https://zpl.io/bzNdyMl

Once the user clicks on the flag icon, they are presented with a modal which allows them to select if they are confident that the identification is incorrect.
https://zpl.io/bzAxxkX

If the user clicks no, it functions as a cancel and the modal closes.
If the user clicks yes, then the user is immediately taken to the failure screen:
![ARCamera-5-SpeciesIDFailed-iPhone8@2x](https://user-images.githubusercontent.com/44380775/60364413-f3742800-999a-11e9-9637-130aa3c3cde4.png)

Things to note:
- if the user leveled up, earned badges, and/or completed a challenge for the observation that they just marked as incorrect, all of those need to be reset to their previous states when the observation is marked incorrect, as if that observation was never made
- if the observation marked incorrect was a new species observation, it should be removed from the user's observations.
- if the observation marked incorrect was a resighted species observation, it should NOT be removed from the user's observations.

**Comment by albullington** [comment]
@abhasinat where can I find the flag icon? I looked through Google Drive but I'm not seeing it.

**Comment by abhasinat** [comment]
It's under 5_ARCamera as "icon-flagidentification"
https://drive.google.com/drive/u/1/folders/1K31PyCA4LNB9eSOGEdLqi9JLlC1A0-I1
