### ISSUE TITLE
Seek giving weird ID suggestions

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#117]
eg https://twitter.com/kimmymolinaro/status/1145808264451563525

<img width="598" alt="image" src="https://user-images.githubusercontent.com/15896181/60531774-8caf8100-9cb0-11e9-91a2-f4977a15ef83.png">

@albullington said "I suspect there’s something buggy in the cameraroll API since this seems to only be affecting a few people. the react native upgrade included a few changes to the cameraroll."

**Comment by albullington** [comment]
Upgraded camera roll library to @1.1.1 to see if that works better

**Comment by albullington** [comment]
This might be related to issue [#123](https://github.com/inaturalist/SeekReactNative/issues/123), even though this is on the Species Detail screen. If this user had a photo of their dad with the wrong metadata, it would have loaded this photo every time.
