### ISSUE TITLE
User unable to add observations

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#124]
A user says "So, the green section in Home never loads, I just see the ever revolving loading symbol. As you can see, my location is turned in and specified, but still no observations saved. I've even tried ubinsyalling and reinstalling the app. As for the other issue, you can see that I am connected to the internet, but the data on the species won't load. Doesn't matter if it's wifi or though my data, same issue. I have an LG Stylo 4 running Android 8.1.0" This should be version 2.2.2, and the user is allowing Seek to access their location.

![Screenshot_2019-07-24-12-42-18](https://user-images.githubusercontent.com/15896181/61817823-4ad3af80-ae04-11e9-8036-28c35c76888d.png)

![Screenshot_2019-07-24-12-43-39](https://user-images.githubusercontent.com/15896181/61817745-19f37a80-ae04-11e9-89a4-9aec26b3fc2e.png)

![Screenshot_2019-07-24-12-43-00](https://user-images.githubusercontent.com/15896181/61817746-1a8c1100-ae04-11e9-8788-160fdd0eeee6.png)

![Screenshot_2019-07-24-12-43-55](https://user-images.githubusercontent.com/15896181/61817747-1a8c1100-ae04-11e9-865d-e706e3c18b39.png)

![Screenshot_2019-07-24-12-39-51](https://user-images.githubusercontent.com/15896181/61817748-1a8c1100-ae04-11e9-9885-7d844c1037a1.png)

**Comment by albullington** [comment]
@tiwane do you think you would be able to ask the user what the sequence of events is here -- which screens they are seeing in which order? 

I'm curious whether the Great Rhododendron screen is something they are accessing from My Observations or from the Species Nearby/Home Screen. If it's the latter, it means their location permissions are indeed working correctly and it's simply the wrong messages that are being displayed -- they would need location working to even access that screen.

I'm also curious whether they can make observations from their camera roll, assuming their AR camera is the part that isn't correctly fetching location.

And I'd like to know if Blue Ridge is their actual location or whether Blue Ridge is something they were able to select from the Location Picker.

**Comment by albullington** [comment]
@abhasinat for the Great Rhododendron species detail screen above, I think we could use an error state that shows up when a user doesn't have location permissions enabled. I've been using the "no internet" error state for both location permissions off and no internet, but that's a bit misleading.
