### ISSUE TITLE
Make it more clear to users what logging in to iNat does and doesn't mean

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#130]
Not sure how much can be done here, but from help@inat I've noticed that users:

a) think that by signing in to iNat, their observations are automatically saved on iNat and will sync to Seek on another device if they sign in there. 

b) that they can restore their observations from iNat if they delete Seek and sign in again.

c) That they need to sign in to iNat to use Seek (I think @abhasinat is already working on a UI fix to de-emphasize this)

Possible solutions, but please add yours:

- add text to the log in/sign up screen that makes clear observations will be lost if the app is deleted.

- generate a notification when someone signs in to iNat for the first time that leads to a screen which explains what using iNat with Seek really means (happy to help wordsmith)

**Comment by abhasinat** [comment]
Ok. I think (a) and (b) can be solved with a better screen that shows up immediately after a user logs in to Seek. This would replace the "Welcome to Seek" screen. I can work on this.

A fix for (c) should already be implemented by @albullington - the "continue without signing in" button is now the same size as the other two.

**Comment by tiwane** [comment]
Thanks!

**Comment by albullington** [comment]
@abhasinat Noting on (c) that I was testing with a friend this week, and he didn't notice the "continue without signing in" button even with the updated UI. His reaction was basically, "aww bummer, I have to sign up to use this?" until I told him he could skip. Might be worth doing some more user research / experimentation on a clearer UX for that screen.

**Comment by abhasinat** [comment]
@albullington heads up that the redesign for the landing page after users log in with iNat on Seek is on Zeplin.

**Comment by albullington** [comment]
Updated the [login success screen](https://zpl.io/V0Lqpzm) with the new text to clarify that observations will be lost if the app is deleted. Closing this issue for now since that's the current action item (though I'm sure we can keep improving on this).
