### ISSUE TITLE
Include slime molds under "Other species" in My Observations 

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/SeekReactNative#142]
Slime molds currently do not appear in My Observations. They should appear in the "Other Species" category (to be updated in #140).

To quickly replicate, point the Seek camera at this iNat observation image: https://www.inaturalist.org/photos/8459986

Once captured at species level, go to My Observations, scroll to "Other Species" and see "You haven't observed any other [species] yet!"

Screen shots below. 
![IMG_8225](https://user-images.githubusercontent.com/7501183/63711174-d2984980-c808-11e9-9c14-c863ddbb69ec.PNG)

![IMG_8226](https://user-images.githubusercontent.com/7501183/63711188-d88e2a80-c808-11e9-8d2f-5478cf903ce6.jpg)

**Comment by albullington** [comment]
@carrieseltzer Awesome, I don't think I ever would have noticed this. Appreciate the thorough (and colorful) example. Looks like we needed to add an edge case for protozoans -- I was assuming everything in "other" was animalia. Are there any other species a user could observe on Seek that are not animalia or protozoans?

**Comment by svshepherd** [comment]
Red, brown algae

**Comment by albullington** [comment]
I added the kelp kingdom to the list of "other" iconic taxon ids we should check for. Closing this for now, but I'll add other ids if anyone finds anything that's not showing up properly in the observations list.
