### ISSUE TITLE
Seek Observation Location doesn't show up in Range Map Detail Page

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#147]
On the Species Detail page, the range map shows the location of where I saw the species in Seek, which is working great.
![IMG_2720](https://user-images.githubusercontent.com/44380775/64291569-547d2680-cf1d-11e9-9f14-a5a4e0b0c545.PNG)

But when I click into the range map, the map is centered on where I made the observation (which is great), but the "Seek Observation Location" camera icon seems to disappear. If I zoom out, the current location pin is still visible, so only the observation location is missing.
![IMG_2721](https://user-images.githubusercontent.com/44380775/64291608-6bbc1400-cf1d-11e9-8892-ecb98312a5b5.PNG)
![IMG_2722](https://user-images.githubusercontent.com/44380775/64291618-74144f00-cf1d-11e9-96e6-2952892e0c0f.PNG)

Both icons should be visible once a user clicks into the range map, and if they are at the same location, the current location pin should be on top of the observation location camera icon. The map should still center on where the user made the observation in Seek.
![Species-2-RangeMap-iPhone8 Copy 3@2x](https://user-images.githubusercontent.com/44380775/64291822-e38a3e80-cf1d-11e9-92b3-0bdb2169b22b.png)

**Comment by albullington** [comment]
Closing because I still haven't been able to replicate this. It works as expected on my devices.

**Comment by abhasinat** [comment]
Strange! I just tested again and looks like the range map camera icon issue (where no camera icon appears) _only_ happens for me when I directly click the map to view the range map. When I click the "view range map" button, the camera icon shows up! Can you replicate?
