### ISSUE TITLE
Make "Near Place" text more translatable

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#173]
Text like [this](https://github.com/inaturalist/SeekReactNative/blob/master/components/Species/INatObs.js#L97) is hard to translate:
```
<Text style={styles.secondHeaderText}>
  {i18n.t( "species_detail.near" )}
  {" "}
  {location}
</Text>
```

In French this could be "Près d'Oakland," "Près de la California," "Près de Paris," or a few other forms depending on whether the place name begins with a vowel and whether the place generally has an article. In Japanese the order is different, something more like "Oakland no chikaku."

At minimum, I'd suggest making this a more completely translatable text, like `Near {{place_name}}`, but dealing with the French cases might require either some very complicated variables, or just going with something simpler like "Near Observation" or "Near Observation Location"

See Crowdin discussion at https://crowdin.com/translate/seek/4/en-ja#1354

**Comment by albullington** [comment]
@abhasinat any preferences on how to simplify this text? (It's the Nearby Location text on the Species Detail screen under the iNaturalist Observations header. Could we use "Nearby" and get rid of the location name altogether?

**Comment by abhasinat** [comment]
Yep, replacing "Near [Location]" with "Nearby" is fine with me.
