### ISSUE TITLE
Not including time when posting to iNat

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#174]
Currently when posting to iNat, iNat is receiving `observed_on_string` values like `2019-12-04` for observations made using the Seek camera and observations made by importing photos. Apparently excluding the time is not intentional, so if we intend to include the time, we should include that.

v2.3.10 (78), Android 10, pixel 3

**Comment by albullington** [comment]
Moved date formatting into the actual UI instead of formatting in local state.
