### ISSUE TITLE
When importing a photo, don't write anything back out to the gallery

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#176]
In Android (v2.3.10 (78), android 10, pixel 3), when I import a photo, Seek writes a smaller copy of that photo back out to my device folders. This seems kind of silly since I just imported the photo from the same place. If we need to make cutdowns of these images, lets store them in app storage where the user doesn't have to worry about them.

**Comment by albullington** [comment]
@kueda is there a specific directory where app storage exists on Android that I should be using? I'm currently writing thumbnails to an external storage folder called Seek/Pictures. This solves the problem where users delete the wrong photo in their camera roll and then see a blank photo in their MyObservations screen, which used to be a pretty frequent complaint. 

On iOS, I'm writing thumbnails into Seek/Pictures in the document directory which does the trick of keeping thumbnails out of the camera roll.

Should I switch to using internal storage on Android?

**Comment by kueda** [comment]
Yes, I think we should be using internal storage for this. If you're using external, you're also running the risk of losing those photos when the user or the OS decides they want to free some space by deleting caches and such.
