### ISSUE TITLE
HTML entities are not rendered in About

### ISSUE THREAD

**Issue by olivierlacan** [inaturalist/SeekReactNative#206]
Noticed this on the [Tsutsusi Azalea][1] page on the third line of the **About** section: 
![image](https://user-images.githubusercontent.com/65950/75621698-94883380-5b65-11ea-8cbc-9cad302ea784.png)

Seems like the `&amp;` ampersand character wasn't properly rendered as HTML. Comparatively the iNatural native iOS app renders the same text fine: 
![image](https://user-images.githubusercontent.com/65950/75621730-14160280-5b66-11ea-8f4a-d20051058ae0.png)

[1]: https://www.inaturalist.org/taxa/208830-Rhododendron-indicum

**Comment by albullington** [comment]
Thanks for pointing this out. We're incorporating a fix into the next release (2.4.7). Please let us know if you find examples of HTML entities that aren't working aside from ampersands, so we can fix those too.
