### ISSUE TITLE
Match screen common ancestor text should not enforce word order

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#211]
[Currently](https://github.com/inaturalist/SeekReactNative/blob/15405a2e1702258a227370c15b062f682dd0ae9c/components/Match/MatchContainer.js#L76) if we have a common ancestor on the match screen, we show the text "WE BELIEVE THIS IS A MEMBER OF" and then we concatenate a string for the rank, like "THE GENUS" followed by the name of the ancestor taxon in a different style. This isn't quite translatable in languages where the "of" might be translated differently depending on the article used with the rank, and/or it makes it hard to understand how text like "the genus" will be used. Can we shift to using a more complete strings, e.g. "WE BELIEVE THIS IS A MEMBER OF THE GENUS" and "WE BELIEVE THIS IS A MEMBER OF THE FAMILY", etc.?

**Comment by kueda** [comment]
FWIW, `We believe this is a member of the {{ancestorRank}}` is better but still hard to translate without knowing whether `ancestorRank` begins with a vowel, what its gender is, etc. IMO, strings like this would be preferrable:

```json
"we_believe_genus": "We believe this is a member of the genus",
"we_believe_family": "We believe this is a member of the family",
"we_believe_order": "We believe this is a member of the order",
"we_believe_class": "We believe this is a member of the class",
"we_believe_phylum": "We believe this is a member of the phylum",
"we_believe_kingdom": "We believe this is a member of the kingdom"
```

**Comment by albullington** [comment]
Updated the en.json file in CrowdIn to include the full sentences (we're only showing the rank for genus through class).
