### ISSUE TITLE
show taxonomy also when internet is unavailable 

### ISSUE THREAD

**Issue by joergmlpts** [inaturalist/SeekReactNative#224]
"View Species" requires internet access and I do understand that its data is obtained from the iNat API.

![taxonomy](https://user-images.githubusercontent.com/66563749/83973877-28247b00-a89e-11ea-9629-233a009ecf91.jpg)

Besides number of observations, maps and more, "View Species" shows the taxonomy from kingdom down to species. Could Seek show the taxonomy for its identification also when internet access is not available? The taxonomy is already known to the app. In the field, in remote areas without cell service, it would be good to see all information that Seek has on an organism.

**Comment by albullington** [comment]
Yes, thanks for this suggestion. We're working on adding this into the next release, 2.8.3.
