### ISSUE TITLE
Romanian pluralization

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#235]
Romanian has unique pluralizations that we just started supporting on the web: https://github.com/inaturalist/inaturalist/commit/9202d58162697bdea3a6ef4baceaa06d2f475706. This came out of a conversation with a translator at https://forum.inaturalist.org/t/strings-with-plurals-in-romanian/14189

To support Romanian translations in Seek, I think we'll need to update i18n.js to match. Also note that that commit improves pluralization handling for fractions, since my original port from a corresponding Ruby library was not doing *quite* the same thing as the Ruby equivalent.

**Comment by albullington** [comment]
Added Romanian pluralization, including the fraction updates.
