### ISSUE TITLE
Add Personal Info consent and policy consent checkboxes to signup form

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#239]
There are some [upcoming changes](https://support.google.com/googleplay/android-developer/answer/9876714) to the Play Store's policies on user-generated content that we should try to comply with. We met today to discuss what to do, and this was one change we agreed on.

On the "SIGN UP FOR INATURALIST" form,

- [x] Add a checkbox below the licensing checkbox that reads, "I consent to allow iNaturalist to store and process limited kinds of personal information about me in order to manage my account." My preference would be for it to also have a "Learn More" link that opens a popup with the title "About Personal Information" and the content "We store personal information like usernames and email addresses in order to manage accounts on this site, and to comply with privacy laws, we need you to check this box to indicate that you consent to this use of personal information. To learn more about what information we collect and how we use it, please see our <a href='%{privacy_url}' target='_blank'>Privacy Policy</a> and our <a href='%{terms_url}' target='_blank'>Terms of Service</a>." The popup is not strictly necessary, but it would be nice to have parity with the website. If links can't be used, I guess we need those clicks to open the in-app versions. This checkbox *must* be checked to enable the "Next" button.
- [x] Replace the PP & ToS links with another checkbox that reads, "I agree to the [Terms of Service](https://www.inaturalist.org/terms) and [Privacy Policy](https://www.inaturalist.org/privacy), and I have reviewed the [Community Guidelines](https://www.inaturalist.org/pages/community+guidelines)." This does not need a "Learn More" popup, but it also must be checked to enable to the "Next" button. Again, if we can't show links, we should use the in-app versions. I don't think including the Community Guidelines is necessary for compliance with the Play Store policies, but it's a definite nice-to-have
- [x] Change the licensing option so it reads, "Yes, license my content so scientists can use my data (recommended)." IMO, this would really benefit from a "Learn More" modal like we use on the web b/c this is *not* obvious to most people.

Can't remember if we talked about dealing with this stuff on separate screens or not. I have no preference about that or how this looks, only that we "require that users accept the app's terms of use and/or user policy before users can create or upload UGC" as Google seems to [want us to](https://support.google.com/googleplay/android-developer/answer/9876937).

**Comment by albullington** [comment]
@abhasinat what do you think about these "Learn More" popups?

**Comment by albullington** [comment]
Added "Learn more" popups to the licensing and data storage sections.
