### ISSUE TITLE
Update Second-level bullets UI for Challenge Detail Screen

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#248]
Here's an updated UI for the second level bullets in challenge detail. I've added `img-bullet-small` to 3_Challenges/iNat Stats to use for this. All bullets and text should have the same sizing and spacing, hopefully this covers all of the bases. Let me know if you have questions, happy to clarify if something is unclear.

![BulletsUI-Update@2x](https://user-images.githubusercontent.com/44380775/90054011-1c837500-dc90-11ea-82ef-ed45c51eaaab.png)

**Comment by albullington** [comment]
Hey @abhasinat, this design is a little different from this one: 

https://app.zeplin.io/project/5bd385bce9f15622d2ef10c2/screen/5f16059cf2c6c18dbf3b20b3. I'm not sure which is the source of truth for whether "Find any 3 aquatic birds" should be nested under a bullet and whether "2 observed so far" should be in line with the other observed counts. 

This design also doesn't indicate where the checklist icon should appear if the user has seen all three aquatic birds. Can you put whatever the final design is on Zeplin so I can get the margins for the entire design, not just the parts you highlighted above?

**Comment by abhasinat** [comment]
Ah, I see the error, I accidentally shifted the primary bullets above and below the secondary bullets to the left before exporting. Thanks for catching that! What's on Zeplin is correct, and no margins should be changing in this design from previous designs. Here's the corrected screenshot that should now be the same as what's on Zeplin:

![BulletsUI-Update@2x](https://user-images.githubusercontent.com/44380775/90453616-f3a31b80-e0a5-11ea-94d7-d32d9c9ab31a.png)
