### ISSUE TITLE
Android: screen flickers crazily for a few seconds when you switch languages, then freezes

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#249]
Version 2.8.4 (135)

Change the language in the app's Settings screen and it will flicker like crazy for a few seconds. App freezes and becomes unusable after that, I need to force quit it. 

Doesn't happen in iOS. 

Log file, in case it's helpful. 
[debug-seek (2).log](https://github.com/inaturalist/SeekReactNative/files/5072642/debug-seek.2.log)

**Comment by albullington** [comment]
It would be helpful to get some more information here -- what is the user's device language and what language are they trying to switch into?

**Comment by albullington** [comment]
@tiwane added a fix for this in v2.9.1, but let me know if you hear any other reports of this.

**Comment by tiwane** [comment]
Will do, thanks!
