### ISSUE TITLE
Can I download the Seek Hierarchical Classification model?

### ISSUE THREAD

**Issue by davodogster** [inaturalist/SeekReactNative#253]
Hi guys, can I download the Seek Hierarchical Classification model somewhere? I would love to run it locally on my machine - I work in Forestry Research in NZ. I think it's a better model compared to the Tensorflow insect species model.

It's hierarchical because if it can't identify the species, it tries to pick the genus / order etc.

**Comment by albullington** [comment]
Hi @davodogster, we have no plans to publicly share the model. We are currently working on creating sample model and taxonomy files that can be used to run the Seek repo locally.
