### ISSUE TITLE
Camera still does not work on Xiaomi phone

### ISSUE THREAD

**Issue by Shellfishgene** [inaturalist/SeekReactNative#269]
Hi!
On my Xiaomi Mi Note 10 Lite running MiUI Global 12.0.1 the camera does not work despite being mentioned as fixed in the release info. I still get the error `Attempt to invoke virutal method 'int.org.inaturalit.inatcamer.ui.Size.getWidth()' on a null object reference`.
The version shown in the Seek info screen is `2.10.3 (149)`.

**Comment by albullington** [comment]
HI @Shellfishgene, would you be able to send some camera debug logs to help+seek@inaturalist.org? You'll need to log into iNaturalist on Seek, then navigate to the About screen. You can tap on the latest Seek version number to access the debug log screen.

**Comment by dgilperez** [comment]
Hi! I am facing the same issue for weeks. I sent the logs a couple of weeks ago to the aforementioned email, no response. Anything else I can do to help?

**Comment by albullington** [comment]
Hi @dgilperez and @Shellfishgene, we created a new beta release last week which has more comprehensive log files for this issue. If you're able to download the beta and send a fresh set of log files to help+seek@inaturalist.org, that would help us resolve the issue more quickly.

**Comment by dgilperez** [comment]
Right away ...

**Comment by dgilperez** [comment]
Hmm I don't find the beta / apk to install - where should I download it from?

**Comment by albullington** [comment]
It's in the Google Play store. Are you already a beta tester? If not, you will need to sign up here: https://play.google.com/apps/testing/org.inaturalist.seek

**Comment by Shellfishgene** [comment]
Worked for me, sent new logs.
If it helps: Sometimes when I open the camera after starting Seek it looks normal with the shutter and help button etc. except that the screen below is just black. Pressing the shutter gets me the loading animation circle that never finishes. This happens about half the time, the other half of tries I get the error message instead.

**Comment by dgilperez** [comment]
Thanks! Joined the beta and sent the logs. And I am also experiencing the
same behavior with random black camera and other times width error.

**Comment by albullington** [comment]
This should be fixed in Seek version 2.10.4, which is currently in beta and will be released in the next week. Closing this issue but feel free to reopen if you run into further issues with the Xiaomi camera.

**Comment by Shellfishgene** [comment]
Can confirm it works now, thanks!

**Comment by dgilperez** [comment]
Very happy to report this working :D
