### ISSUE TITLE
Sometimes taxonomy & description are not loading in species details page when other languages are selected.

### ISSUE THREAD

**Issue by Nu1Wijayaweera** [inaturalist/SeekReactNative#275]
I found that, when I change the language to Sinhala, only some of my observations show local Sinhala common names (even when there's a Sinhala common name on iNaturalist) and when I click on one to view the details page, that also shows the Scientific Name without the common name.

Also, when there's no local (Sinhala) Wikipedia page for that species, it only shows a link & does not load the taxonomy below.

Also, when I click on a species from similar species & if that species has a local Wikipedia page, then it shows the taxonomy but when I click another one which doesn't have a Wikipedia page, it shows the same taxonomy of the previous species with a Wikipedia page.

Is it possible to load the taxonomy regardless of whether that species has a Wikipedia page or not? Also, is it possible to show local common names of the selected locale when such is available?

I assume:

"I noticed that when English is selected as the language, everything works okay. However, when I select Sinhala as the language this issue occurs.

The issue is, whenever I navigate to the species details page via "my observations", it tries to pull Wikipedia pages in selected locale but usually there aren't any Sinhala Wikipedia pages for species. So, when this happens, it kind of skip loading the taxonomy section. So, most of the time I can only see an empty description with no taxonomy.

I think this issue is there for species without a Wikipedia page. I'm not sure though. I hope this helps."

**Comment by albullington** [comment]
It sounds like you’re experiencing two separate issues.

Common names:
1. For this issue, we have a very limited set of Sinhala common names available in Seek (currently, less than 70 names). These are displaying correctly as far as I can tell, so feel free to add a screenshot of your Observations screen here to clarify which common names are available in iNat but not showing in Seek. If you’re checking for common names immediately after switching from English to Sinhala, you may need to give the app a moment to load (or possibly restart the app) to be sure the Sinhala names are displayed.
2. If you’d like to add more Sinhala common names to iNaturalist & Seek, I’d recommend contacting help@inaturalist.org so we can set you up with the correct csv template.

Taxonomy List:
1. There was an issue where the taxonomy list wasn’t loading for species without a common name. We’ll have a fix for this in the 2.10.5 release.

Let me know if this solves your issues.

**Comment by Nu1Wijayaweera** [comment]
Yes, I kinda wrote about multiple issues there. Sorry for the inconvenience.

Common Names:

1. I'm sorry, but I can't agree with you on this. For example, take "Ixora coccinea". This has a Sinhala name on iNaturalist, which is "රත්මල්", but it doesn't show up in Seek in specific places. What I mean by this is that it shows the common name "රත්මල්" on "Similar Species" scroll list at the bottom of the details page. Also, the common names are correctly showing on the scroll list on the top of the home page. However, most common names are not showing in "My Observations" list. Also, such common names are not showing in specific species details pages. However, this doesn't happen for "Averrhoa carambola". For this species, everything works fine. So, I don't know how it happens. However, an issue is there for sure.

[Image]

[Image]

[Image]

2. Thanks.

Taxonomy List:

1: Great! Thanks.
________________________________

**Comment by albullington** [comment]
Thanks for sharing a concrete example. I believe you tried to post a few screenshots here, but if so, I can't see them.

As for the discrepancies you're seeing in common names like රත්මල්, what you're seeing is the difference between common names which are available online vs. offline. We update the offline names in Seek every month or two, so if a name like රත්මල් was added to iNaturalist more recently it will not be displayed in Seek immediately.

Our preference is to have the offline names as the single source of truth, since this encourages users to take Seek into the woods / away from cell service. I'll make sure we're more consistent in showing only the offline names throughout Seek, including the Similar Species and Species Nearby lists.

**Comment by Nu1Wijayaweera** [comment]
I didn't know that seek is using an offline set of common names. Thank you for letting me know. I think then that issue will get solved when you update offline common names list.

Regarding screenshots, yes, I replied to the email, so, it seems like either GitHub doesn't allow images or those didn't get attached properly. Either way, I don't think those are necessary now, the explanation regarding offline common names makes sense.

Then you may consider this issue is solved. Thank you for the explanation and I'm sorry for any inconvenience caused by this.

Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by albullington** [comment]
Awesome. I'll close this for now, and feel free to reopen if the common names issue isn't resolved in the next month or two.
