### ISSUE TITLE
Linking configured in multiple places

### ISSUE THREAD

**Issue by albullington** [inaturalist/SeekReactNative#294]
**Describe the bug**
```
com.facebook.react.common.JavascriptException: Error: Looks like you have configured linking in multiple places. This is likely an error since deep links should only be handled in one place to avoid conflicts. Make sure that:
- You are not using both 'linking' prop and 'useLinking'
- You don't have 'useLinking' in multiple components
- You have set 'android:launchMode=singleTask' in the '<activity />' section of the 'AndroidManifest.xml' file to avoid launching multiple instances
```
**To Reproduce**
- TBD

**Expected behavior**
Links should be configured properly, and users should be able to use deep links in the app without crashes.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Android Huawei Y9 Prime 2019, Motorola Moto G(4) Plus
 - Version 2.10.7

**Additional context**
- Linking is set up for two purposes: 1) quick actions to open the AR camera and 2) showing Google Play Store review prompt after a certain number of species are identified. The linking prop is passed into the NavigationContainer for deep linking to the AR camera, and there is additional linking code on the SplashScreen.
- **You are not using both 'linking' prop and 'useLinking'** this one is probably the issue since we're using both of these for quick actions

**Comment by albullington** [comment]
Removed `linkTo` method and `linking` prop in v2.11.3

**Comment by EduTel** [comment]
what was the problem? How did they solve it?
