### ISSUE TITLE
Display iNaturalist username when one is logged in to iNat

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#317]
**Is your feature request related to a problem? Please describe.**
Currently, if someone is logged in to iNaturalist in Seek, there is no way to know which iNat account they're logged into. For users with more than one account (eg teachers or users who've accidentally made more than one account) it's confusing and there's no way to know which account they're currently using with Seek. 

**Describe the solution you'd like**
On the iNaturalist screen, if someone is logged in to iNaturalist, display the username of the account they're logged in with. I suppose the logged in text could be amended to something like "You are logged in to Seek with the iNaturalist account [username]" but I defer to @abhasinat to design decisions.

**Describe alternatives you've considered**
Displaying the iNat account name in Settings, but the iNaturalist screen seems more appropriate.

**Comment by albullington** [comment]
Feature released in v2.12.6 (Home Screen login card + iNaturalist screen)
