### ISSUE TITLE
Species nearby won't load on results screen

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#322]
**Describe the bug**
Tapping on "species seen nearby" returns no results when there should be results.

**To Reproduce**
1. Make an observation of a common nearby species and make sure the app can only ID it to genus (eg https://www.inaturalist.org/observations/73080546 if you're in the Bay Area)
2. On the results screen tap on "Tap to load species nearby"
3. You see "Looks like there haven't been many species..." even though [there are plenty](https://www.inaturalist.org/observations?hrank=species&place_id=54321&subview=map&taxon_id=52932).

**Expected behavior**
I expect to see a list of species seen nearby as shown on iNat. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.4
 - Version 2.12.2 (177)

**Comment by albullington** [comment]
It looks like the taxa/nearby endpoint is returning empty results when a `taxon_id` is added to the query string. We use the taxon id on this screen to filter for "species nearby within this taxon."

As an example, we're using this type of query string in Seek: `per_page=20&lat=37.84&lng=-122.31&observed_on=Wed Apr 07 2021 16:31:48 GMT-0700 (PDT)&seek_exceptions=true&locale=en-US&taxon_id=372854&all_photos=true`. I can remove `taxon_id` from the parameters and see results (similar to what users are seeing on the Home Screen species nearby card).

Oddly, the `taxon_id` parameter seems to be working fine with our staging api. I can use this same query string on staging and see results.

Maybe @pleary or @kueda have input here?

**Comment by kueda** [comment]
For the record, this seems to have been a problem with populating the Redis frequencies: for some reason we only added leaves without ancestors. We just re-ran the import and things seem to be working again. Convo for historical purposes is at https://inaturalist.slack.com/archives/C02F8QXTU/p1617906365031900
