### ISSUE TITLE
Try to use coarser place names if there is no "locality" for a user's coordinates

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#323]
**Is your feature request related to a problem? Please describe.**
In some parts of the world, we display "Undefined location". eg St. Martin:

![image](https://user-images.githubusercontent.com/15896181/114106001-b7b20600-9882-11eb-9af8-f2ff9461b342.png)

This has cause some confusion with users, who think the app is not obtaining their location accurately. Plus it would be nice if we could display some sort of relevant name for almost anywhere. 

**Describe the solution you'd like**
After discussing with @albullington, it's possible we can show a broader name if "locality" is not available, which I think would be good.

**Describe alternatives you've considered**
I have not considered any.

**Comment by albullington** [comment]
Fixed in commit [d33d6e](https://github.com/inaturalist/SeekReactNative/commit/d33d6e24e1a29351b300b1edbc8ab0a29d618655)
