### ISSUE TITLE
Don't cut off text

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#326]
From: https://forum.inaturalist.org/t/text-is-cut-off-on-observation-detail-quality-grade-section/21771/4

In French, this text is cut off. Can we wrap text if it's more than one line?

![image](https://user-images.githubusercontent.com/15896181/114463217-fe607280-9b98-11eb-9836-9aa7855a94f9.png)

**Comment by albullington** [comment]
Fixed in v2.12.4
