### ISSUE TITLE
Remove infinitely growing navigation stacks

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#33]
Some uses of `navigation.push` allow the navigation stack to grow indefinitely which will lead to crashes, e.g.

1. Open the camera from the footer (push)
1. Take a photo
1. Identify the photo
1. Land on the MatchScreen
1. Open the camera from the footer (push)

I suspect there are a number of ways we could address this, including use of modals and `navigate` instead of `push`. Another might be to change the IA, e.g. remove the footer from any screen you can get to from the camera, and ensure all screens from the camera can only be exited by going back or via `navigate` to get out of the current navigation stack.

**Comment by albullington** [comment]
Should be fixed in commit [7fd511a](https://github.com/inaturalist/SeekReactNative/commit/7fd511a2736fdc812b2ac42b0781bf9f7dee9f96)
