### ISSUE TITLE
Seasonality setting reverts to default after force quitting and reopening app.

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#332]
**Describe the bug**
Seasonality setting reverts to default after force quitting and reopening app.

**To Reproduce**
1. Go to Settings and choose to see seasonality based on your location.
2.Force quit app then reopen
3. Seasonality setting is back at default (global)

**Expected behavior**
I expect my chosen Setting to stay as is until I change it.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 14.5
 - Version 2.12.4

**Comment by albullington** [comment]
Closed in v2.12.5
