### ISSUE TITLE
September 2019 Freshwater Challenge - two fixes needed for bulrushes

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#344]
1. The challenge's description says "bulbushes", but it should read "bulrushes".

2. Making an observation of a bulrush doesn't count toward the challenge. I think we can use https://www.inaturalist.org/taxa/47161-Cyperaceae as the taxon here - most grow in moist areas, and maybe amend the Mission text to "...lillies, bulrushes, sedges, and cattails."

**Comment by albullington** [comment]
Should be fixed in v2.12.7
