### ISSUE TITLE
Improve autocapture

### ISSUE THREAD

**Issue by albullington** [inaturalist/SeekReactNative#355]
**Is your feature request related to a problem? Please describe.**
Autocapture works well in that the camera automatically takes a photo when a species is predicted. However, it does lead to a lot of blurry photos like [this one](https://www.inaturalist.org/observations/83195897) since the photo is captured before a user taps to focus.

**Describe the solution you'd like**
At minimum, I'd like a toggle in the AR camera UI to switch autocapture off quickly when I'm in the field (instead of trying to take the same photo multiple times, or swiping out of Seek over to the iOS camera, which is what I often ended up doing). It didn't occur to me until now that I could use the settings button in the AR camera to turn off autocapture in ~3 taps (settings screen -> autocapture toggle -> back to camera).

**Describe alternatives you've considered**
Ideally, we would be able to delay taking a photo with autocapture until the camera is in focus, but I'm not sure what the implementation of this would look like. Maybe we can add an option to autofocus when we call `takePictureAsync` in `react-native-inat-camera`?

**Additional context**
N/A

**Comment by jtklein** [comment]
Autofocus is now the default with vision-camera.
