### ISSUE TITLE
New Species Nearby section on Challenge Detail screen

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#363]
On the challenge detail screen, it would be a good idea for users to be able to load species nearby that they could observe for the challenge.

**Design**
Similar to how we added the “Species observed” section that was adapted from species nearby on the Home Screen, please add a new section called “Species Nearby in this Challenge” directly above the "Species observed" section.

![image](https://user-images.githubusercontent.com/44380775/124656500-e9793f80-de66-11eb-9179-f4b18685e946.png)
![image](https://user-images.githubusercontent.com/44380775/124656561-fc8c0f80-de66-11eb-9d96-b9ee82fe6bbd.png)

This will have the same UX as the “Species Nearby in this Taxon” section from the higher-taxa match screen (the blue match screen, above) except with a few styling changes to better fit the challenge detail page (same as the UI changes we made for the “Species Observed” section). Species names text should be black and the background should be white instead of blue. Additionally, the “Tap to view species nearby” text should also be black on the white background.

**Functionality**
Once a user taps “Tap to load species nearby,” the species that are generated should be:

- All taxa in the challenge that are seen nearby (with the same distance radius as everywhere else in Seek)
- _Excluding_ all species that a user has already observed in Seek (since re-sighting a species will not help them get the challenge badge)

**Comment by albullington** [comment]
I might have more questions, but a couple initial questions that come to mind for @abhasinat and @carrieseltzer:

1. Do we want to show species nearby on *all* challenges, or only challenges with less than 100% completion?
2. Is the goal to show all possible species that could count towards a challenge, or do we need to filter out the parts of a challenge a user has seen already? (For example, if a user found everything in a challenge except for fish, should the species nearby list show only fish, or should it show all pieces of the challenge?)
3. What should we show if there are no species found nearby for a particular challenge (or piece of a challenge)? (I imagine we want to be careful with wording here)

**Comment by carrieseltzer** [comment]
I think showing only species that would count towards challenge completion makes sense, so:
1. Only challenges with less than 100% completion
2. Filter out species for fully completed parts of the challenge
3. Something like "No species recorded nearby for this challenge that you have not yet recorded." Just an idea.

**Comment by abhasinat** [comment]
I agree with @carrieseltzer. I would filter out each bullet that has been completed.

Here's a thought for the error state text:
"We found no species nearby in this challenge that you haven't already observed"

**Comment by albullington** [comment]
Released in 2.12.10. Required a couple API changes to make `taxon_id` accept a comma-separated list of values and to add a `without_taxon_id` parameter for filtering a user's existing observations.
