### ISSUE TITLE
A few non-camera UI changes for iPad

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#372]
- [x] when I click a species badge in achievements in landscape mode, I get a black screen I can’t get rid of without quitting the app (so I’m unsure of what the badge modal looks like on landscape). strangely, the modals for the challenge badges below and the level badge at the top seem to show up just fine - this seems to be specific to the species badges.
> - I think iPad is currently locked in landscape so I’m unsure if this is in portrait as well.

- [x] restrict the width of all grouped badges on the achievements screen to 455px
> - for all screen sizes

- [x] on the iNat Stats, About, and Settings screens: restrict the width of all text (excluding images and backgrounds that span the width of the screen) to 455px so text is more readable
> - for now, just on landscape tablets. not sure how this would look, but I think the text is too hard to read when it’s so wide

- [x] when the species detail screen is loading, there’s a brief amount of time where this screen shows up, and it can be visible for a while if the user has limited internet. For the loading state, I would remove the black and gray boxes here and place a black bar on the 1/3 left of the screen, and leave the right 2/3 white, mimicking the backgrounds of each of those sections when they’re loaded. Lastly, I would include loading wheels on this screen while things are being loaded in:
> - one loading wheel centered on the right 2/3 (white part of the screen) while all the info is loading
> - one loading wheel centered on each of the photos on the left, so a user can see how many images are yet to be loaded in.

![IMG_83A2C7EC3ECF-1](https://user-images.githubusercontent.com/44380775/127693661-a4c02091-fe35-4608-b3ef-9984dd6b5ea6.jpeg)

**Comment by albullington** [comment]
@abhasinat per [this issue](https://github.com/inaturalist/SeekReactNative/issues/353), can we use skeleton UI instead of loading wheels for the species detail screen? I personally hate loading wheels in React Native. I think they add a bit of jankiness on most of our screens since they involve state changes, so I often end up removing them. Plus, I think skeleton UI is the more modern way to signal loading.

**Comment by albullington** [comment]
@abhasinat for this one "on the iNat Stats, About, and Settings screens: restrict the width of all text (excluding images and backgrounds that span the width of the screen) to 455px so text is more readable" I'm assuming you also want the text containers centered above the camera icon instead of left aligned?

**Comment by abhasinat** [comment]
@albullington for the skeleton UI - I think the biggest thing for me is having the black background for the left 1/3 of the screen and white background for the right 2/3 rather than the rectangle in the top left corner. I'm okay with whatever skeleton UI you think would be best on top of that. I personally think loading wheels are a good solution on top of this skeleton UI because users understand that something is actually loading and not that something went wrong, but I'm fine with just the skeleton UI if you think that's a better solution.

And yes - text containers centered on screen when the text width is constrained.

**Comment by abhasinat** [comment]
Tested the latest beta.
- Camera flashing issue from before is much better - the smoother experience, even if the ID changes to family/etc. on the 2.5 sec refresh is much better. thanks for making that change!
- About and Achievements pages are looking good.
- Rotation between portrait and landscape is looking fantastic on iPad! I love how seamless it feels.

A few more changes:

- [ ] clicking into a species badge when I've earned a badge- looks like the badge sizing is off.
> - this applies to iPad horizontal, vertical, and iPhone as well
> - however, the empty badge states for species badges and all challenge badges seem to be fine.

> ![IMG_0334](https://user-images.githubusercontent.com/44380775/128757894-e9780106-342b-40ca-b62d-e97701f308f3.PNG)

- [ ] challenges I start using the "start now" or "take the challenge" buttons don't appear in the in progress section of all challenges until I close and restart the app and stay in the not started section before that. ideally, they would show up there right away.

- [ ] The touchbox for the delete observation button on My observations is too big on both portrait/landscape iPad - if I touch the center of the screen to select the observation, the delete obs modal pops up. Please move the touchbox all the way to the right of the observation card or only tappable once a user swipes left for iPad.

- [ ] Please restrict the width of the text containers on the iNat Stats, About, and Settings screens to 455px in Portrait mode as well, across all non-mobile devices only i.e. (tablets, computers, etc). On mobile devices, they should span the width of the screen
> - I would also center the settings screen's text container on the screen for non-mobile devices

- [ ] on the AR camera, please restrict the width of the wrapper around the 7 rank indicator dots to 262px across all devices (this should match the width we have for the 7 dots on landscape iPad)

- [ ] on the Settings screen, please increase the horizontal spacing between the "Automatically take a picture..." text and the switch button to match the spacing between the radio buttons and text above.

**Comment by albullington** [comment]
@abhasinat can you clarify what you want to change for this line?

`on the Settings screen, please increase the horizontal spacing between the "Automatically take a picture..." text and the switch button to match the spacing between the radio buttons and text above.`

I'm reading this as the wanting the space between radio button + text to match the space between switch + text to be equal. Right now they're both set to 10px spacing.

I also think it's helpful to keep this github issue focused on the things that need changing to support iPad, rather than general bugs / enhancements, so I'm going to move the challenges feedback to a separate issue.

**Comment by abhasinat** [comment]
- Splash screen is looking fantastic!
- In general, rotation is looking good and the UI is looking really nice with all the fixes.

A few additional changes:
- [ ] On the My Observations screen, please increase the width of the touchbox to open the species detail screen for each observation to span the width of the screen - i.e. when I tap the white space to the right of an observation on My Observations, it should open the species detail screen for the observation that's in that row.
- [ ] I wasn't clear enough around my fix the 7 rank indicators UI above:
> - Landscape mode was totally fine before. My intention was to make portrait mode match landscape mode better. Please change the UI back to what it was before in landscape mode - the green background on which the rank indicators sit does not need to change at all.
> - In portrait mode on all devices, please restrict the max width of the rank indicators to 262 px. The max width of the rank indicator dots is indicated by the white dotted line below, and where the rank indicators should be on the screen here are in pink. The rank indicator dots can be smaller than 262px if a smaller screen width constrains them, but the max width of the 7 dots on any screen in portrait mode should be 262 px. Hope this is a bit clearer.
> ![Limit width of AR camera dots Portrait](https://user-images.githubusercontent.com/44380775/129285269-b87bac57-eaf2-4689-b70a-26fa46364175.png)
- [ ] For the settings screen, what I mean is to move the text "Automatically take a picture..." to the right by 6px, while leaving the switch to the left of it where it is.
> ![image](https://user-images.githubusercontent.com/44380775/129285669-6996bf7a-7d6d-4d17-956b-67a40e9510a0.png)
