### ISSUE TITLE
Make taxon guesses in AR camera easier to see

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#38]
Low priority, but maybe easy?

The species suggestions in the AR camera are composed of entirely white text, which means they can get lost if the part of the screen is overexposed (which can happen often in smartphone cameras). Would it be possible to add a black outline or something to this text to make it more easy to see in these situations?

**Comment by albullington** [comment]
Added shadows to all text and images. Will be in v2.0.2.
