### ISSUE TITLE
Langauge spontaneously changing for some iOS users

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#385]
**Describe the bug**
Several users, I believe all iOS users whose phones had a default language of English, found that Seek's language setting seemed to spontaneously change to another language. The latest instance was with version 2.12.15 (220) but it also happened in 2.12.9 (199).

**To Reproduce**
Unfortunately there are no reproducible steps.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/15896181/133476692-5e696349-0ba5-4919-87b4-f62a653fe846.png)

**Smartphone (please complete the following information):**
No info. 

**Additional context**

**Comment by tiwane** [comment]
I like that fix.

**Comment by tiwane** [comment]
FWIW we've recently been getting more emails from people who are doing this. If this confirmation modal can be added to the next update that would be great.

**Comment by jtklein** [comment]
The confirmation modal is added.
