### ISSUE TITLE
Crash on My Observations when species has no default photo

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#39]
As reported by @alexshepard. This probably hits existing users disproportionately, as the more taxa they have the more likely some will not have a default photo.

![Simulator Screen Shot - iPhone Xʀ - 2019-04-10 at 11 06 11](https://user-images.githubusercontent.com/22691/55903150-d0975c00-5b81-11e9-91a7-b2341a86958b.png)

**Comment by albullington** [comment]
Fixed in commit [41e7523](https://github.com/inaturalist/SeekReactNative/commit/41e7523d2e2fc951d73309dc64e189191e55de7a)
