### ISSUE TITLE
Show observations without an iconic taxon 

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/SeekReactNative#40]
looks like SeekV2 won’t display observations that don’t have an iconic taxon in the “seek” iconic taxa list: [birds, amphibians, reptiles, mammals, mollusks, arachnids, plants, insects, fungi, fish]

**Comment by albullington** [comment]
Fixed in commit [41e7523](https://github.com/inaturalist/SeekReactNative/commit/41e7523d2e2fc951d73309dc64e189191e55de7a)
