### ISSUE TITLE
crash on my observations when species has no common name

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/SeekReactNative#41]
![Simulator Screen Shot - iPhone Xʀ - 2019-04-10 at 12 34 00](https://user-images.githubusercontent.com/515947/55908251-c5e2c400-5b8d-11e9-9949-6f05bf221091.png)

**Comment by albullington** [comment]
Fixed in commit [41e7523](https://github.com/inaturalist/SeekReactNative/commit/41e7523d2e2fc951d73309dc64e189191e55de7a)
