### ISSUE TITLE
Handle errors from /oauth/token

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#418]
Basically a clone of https://github.com/inaturalist/iNaturalistAndroid/issues/1188

Currently if `/oauth/token` responds with an error, the client seems to do nothing or show a generic error. Instead, let's show the user a useful error. According to the spec, errors should all have the status code `400` and a response body like

```json
{
  "error": "SOME_ERROR_CODE",
  "error_description": "HUMAN-READABLE DESCRIPTION"
}
```

- [x] If requests to `/oauth/token` receive a `400` response, show an alert displaying the `error_description` if present, and if not a generic error message like "Authentication failed"
- [x] Include a `locale` in the POST body when making this request so the server can localize the error responses

**Comment by albullington** [comment]
@kueda is it possible that there's a bug with locale here? It looks to me like when I pass in either `en-US` or `en` for locale, I'm getting back somewhat random error messages -- usually English but also French, Spanish, and Russian.

**Comment by kueda** [comment]
Sorry about that, @albullington. Should be fixed by https://github.com/inaturalist/inaturalist/commit/e0f3480ee4eee1e1bc5f5946cde5e8d4ae96c815.

**Comment by kueda** [comment]
FYI, 48ef5390b94c00a1dcb8239b37028860cb9ef72c deals with 400 responses from the `LoginScreen`, but not on the `SignUpScreen`, where we also make a request to `/oauth/token`. Both need to be ready to deal with this 400 response.
