### ISSUE TITLE
Photo can't be saved

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#427]
**Is this a camera bug?**
If so, please head to [react-native-inat-camera](https://github.com/inaturalist/react-native-inat-camera) library and fill out a bug report there.

**Describe the bug**
Some iOS users, who have been using the app for a while now, can no longer save their photos. 

**To Reproduce**

(May not be complete, as I can't replicate)

1. Take a photo with the Seek camera.
2. Get an error message saying the photo can't be saved.

**Expected behavior**

**Screenshots**
From two different users:

![image](https://user-images.githubusercontent.com/15896181/161661806-cc5711d3-9e79-48cf-97b9-77c5a3e7e069.png)

![image](https://user-images.githubusercontent.com/15896181/161661831-6b0aef7b-eb44-4c39-aa29-5c4ae871ae14.png)

Permissions screenshot from one user:

![image](https://user-images.githubusercontent.com/15896181/161661986-cd01a348-a46c-404e-895f-53a752536289.png)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: unsure
 - Version 2.13.5 (240)

**Additional context**
Add any other context about the problem here (i.e. what language are you using, do you have location settings turned on, did you have cell signal)

**Comment by jtklein** [comment]
I was checking the underlying native errors and they might have been fixed by upgrading third-party dependencies by now. If this error happens again, we can reopen this issue.
