### ISSUE TITLE
`security` breaks build on Linux

### ISSUE THREAD

**Issue by ahstro** [inaturalist/SeekReactNative#432]
When trying to `npm run android` on a machine that doesn't have the [macOS `security` command](https://ss64.com/osx/security.html), e.g. on a Linux machine, the build just crashes 😞 This is the function where it's being used:

https://github.com/inaturalist/SeekReactNative/blob/b5bbf80bb53806dbc1c79f07ce539cbbfedc5d53/android/app/build.gradle#L80-L91

A workaround is to simply not call `getPassword` and just put your plaintext password here:
https://github.com/inaturalist/SeekReactNative/blob/b5bbf80bb53806dbc1c79f07ce539cbbfedc5d53/android/app/build.gradle#L114
But that isn't ideal for many reasons 😅

Not sure what a good solution would be, but I'm willing to try them on my machine if needed 😊

**Comment by jtklein** [comment]
Thank you for your report.
We have now changed the code that retrieves the password. You can now add your password as a gradle property to the build. Now you can add a global gradle.properties with SEEK_RELEASE_KEY_PASSWORD defined, and this will be used before checking the keychain with the security package.
