### ISSUE TITLE
Globalize shortcut text

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#440]
Currently when you long-press on the Seek app icon in Android (and in iOS?) you get a shortcut menu that includes "Seek AR Camera" that drops you directly into the AR camera in Seek. However, this text is not globalized. If your phone is set to use Spanish, that text still reads "Seek AR Camera." I suspect if we globalize the [`title` and `subtitle` attributes in navigationHelpers.js](https://github.com/inaturalist/SeekReactNative/blob/main/utility/navigationHelpers.js#L11) that would deal with the issue in Android, but I'm not sure how this works in iOS.

Also, let's change it to "Seek Camera" instead of "Seek AR Camera" per https://inaturalist.slack.com/archives/C9KMT4MK2/p1651601415197189

**Comment by albullington** [comment]
Updating this in 2.14.0 to globalize the title for Android-only and the subtitle for both.

Changed to Seek Camera in both iOS and Android.

For iOS, I suspect we'll need Localization files for every language in Seek. We're setting this text via Info.plist using:

```
<key>UIApplicationShortcutItemTitle</key>
<string>Seek Camera</string>
```
so I think we'll need to change `<string>Seek Camera</string>` to a variable and add a corresponding key-value pair for each language.

**Comment by jtklein** [comment]
I have added the string to a Resource file for localization that should also be tracked by crowdin.

We should test if translations are automatically provided via the crowdin setup after v2.14.5 is merged into main.
