### ISSUE TITLE
Android: Can't leave Seek by tapping on back button

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#442]
**Is this a camera bug?**
If so, please head to [react-native-inat-camera](https://github.com/inaturalist/react-native-inat-camera) library and fill out a bug report there.

**Describe the bug**
Tapping on the Android back button does not allow you to exit the app.

**To Reproduce**
1. Open Seek. Seek's home screen loads.
2. Tap on something in the side menu or open the camera
3. Tap the back  button and you're returned to the home screen.
4. Tap on the back button to exit the app. Nothing happens.

**Expected behavior**
Tapping on the back button in step 4 should exit the app.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - OS: Android 12
 - Version: 2.13.6 (243)

**Comment by Optilete** [comment]
Can reproduce it on my 
Device: Poco X3 NFC
OS: Android 12
Version: 2.14.2 (252)
Also remarks on Google Play with five likes: 5 mei 2022 'Werkt goed, maar als ik de app geopend heb, krijg ik hem niet meer weg van mijn scherm. Hij wil niet sluiten.' https://play.google.com/store/apps/details?id=org.inaturalist.seek
