### ISSUE TITLE
App freezes when picture taken that isn't IDed to species

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#452]
**Is this a camera bug?**
I don't *think* so. 

**Describe the bug**
Sometimes, when someone takes a photo of an organism that has _not_ been IDed to species, the app screen turns dark and then freezes. 

**To Reproduce**
1. Open Seek camera
2. Scan something and make sure it's not identified to species
3. Take a photo.
4. The "we can't identify to species" screen shows but it's darkened. Can't do anything else in the app, it needs to be closed.

**Expected behavior**
If something can't be identified to speices, I should still be able to use the app.

**Screenshots**

<img width="245" alt="image" src="https://user-images.githubusercontent.com/15896181/174171065-0c05a8b5-3b77-429d-9d1e-0c87f041ab46.png">

**Smartphone (please complete the following information):**
 - Device: Reports from iPhone X, iPHone 12, I could replicate on Pixel 3A
 - OS: iOS 15.5, Android 12
 - Version 2.14.0 (247)

**Additional context**
The screenshot is from a user. I as able to replicate once on my Pixel 3A but that's it. I've tried switching my device's language to Danish but that didn't seem to make a difference.

**Comment by tiwane** [comment]
Since I don't _think_ it's camera related, a log file probably won't help but here's one from my Pixel 3A. https://inaturalist.slack.com/archives/C9KMT4MK2/p1655416109379639

**Comment by albullington** [comment]
@tiwane I haven't been able to replicate this today. Can you tell me anything more about what you're doing before and after going to the camera? Did you open any other screens, take a certain number of photos with the camera before this dark screen popped up, etc?

There's a possibility this could be a modal that's not showing up correctly. Did you take a photo of a species that would count towards a challenge or earn you a level badge?

**Comment by tiwane** [comment]
I was only able to replicate this once on my Pixel 3A and that was some time ago. I think it happened after I made a few observations without closing the app. I've tried to do that since but no dice. 

I haven't been able to get any clear replication details from users who have reported this, but it seems to happen only (or at least nearly only) when they make an observation that is _not_ identified to species. Will keep trying to get more info. Here's a recent report, if that helps.

> I have used Seek for a few years without any problem. Two weeks ago I download iNaturalist and linked it to my Seek login. 
> 
> It has worked ok except in one circumstance. Now if I take a picture of a plant when it is at the Family or Genus level, my iPhone copy of Seek locks up and gives me a greyed out screen. At that point I can not back out of the screen or even close Seek. I have to turn off my phone and restart.  I first noticed this problem identifying plants in an area with out cell service. I thought that was the problem. Today the same problem happened with solid cell service 
> 
> Here is my operating environment
> 
> IPhone 13 Pro
> OS 15.5
> Seek 2.14.1 (248)
> iNaturalist 3.25 build 658
> iNaturalist user name:  [redacted]
> 
> I attached two screen shots. One where I successfully identified a plant to species level. A few minutes later I had a plant only identified to genus level.  The Seek ap locked up when I took the picture. The screen immediately greyed out and locked.  If I back out before I take a picture there is no problem. Once I take a picture it locks up and I can’t get out if Seek - I have to restart phone 
> 
> My wife has an iPhone 11 and it is happening to her also 
> 

![unnamed](https://user-images.githubusercontent.com/15896181/178380187-1b318876-fb96-4979-a7c8-8fb1ef2204c8.jpeg)

![unnamed2](https://user-images.githubusercontent.com/15896181/178380213-466ea090-94bc-43b1-981b-d98a1d084874.jpeg)

**Comment by tiwane** [comment]
OK, I was able to consistently replicate this in both 2.14.1 (248) and 2.14.2 (249). The key, at least for me, seems to be observing a species you've already observed and choosing "keep old photo". Then, when you open the camera again and take a photo of something that Seek can't ID to species (in this case, genus), the app freezes up and grays out. I can close the app and force quit it. It reopens fine after that. 

Screen recording here: https://inaturalist.slack.com/files/U0CPBG8M6/F03PYSL2GE4/untitled.mp4

**Comment by tiwane** [comment]
Also happens if I choose to use the old photo. Also, only happens if I'm using the Seek camera, not importing photos.
