### ISSUE TITLE
documentation about data location

### ISSUE THREAD

**Issue by ntala** [inaturalist/SeekReactNative#470]
I am struggling to understand where to find data from my observations on Seek (on a fairphone where [/e/OS](https://community.e.foundation/) is installed).
I can export all the pictures from Pictures/Seek and the taxonomy.csv file with all the taxons' scientific names in the apk file.
But I am still unable to find where the localized taxons' names (in French in my case) are located and, more crucial for me, where to find the link between the identified taxon and its picture.

I hope not to pollute this issues list with that kind of question but I did not manage to find another way to solve this problem.

**Comment by Optilete** [comment]
Localized taxons' names (like French) are located in the ZIP-file https://www.inaturalist.org/taxa/inaturalist-taxonomy.dwca.zip  https://forum.inaturalist.org/t/using-sql-to-query-inats-dwca-taxonomy-export/29377

**Comment by ntala** [comment]
Thank you !
A part of my problem is solved... But where can I get the detected taxon's ID for a given picture ? Or all the detected taxons ?
I tried to find this data among the pictures exif tags and in the application logfile. I looked after a Seek related database on my phone... Without success.

**Comment by kueda** [comment]
If you are decompiling the app, most of the observational data should be in a Realm database file called `db.realm`. However, the best way to get data out of Seek is to sign in to an iNaturalist account in the app, sync all your observations, and then export your data from iNat using https://www.inaturalist.org/observations/export. We never really intended any users to get at their data through decompilation. If you're really interested in data collection, I recommend using the iNaturalist app. Seek is more of a game and a quick identification app.

**Comment by ntala** [comment]
Hello, I would like to reopen the discussion :
I managed to copy the db.realm file from my phone to my computer.
Sadly, I do not manage to open this file with realm studio... It may be a problem from incompatibility between different Realm database versions.
Could someone tell me which version is the file format used for realm.db on seek ?
Thank you for your help.
