### ISSUE TITLE
the items in the notifications list have no text

### ISSUE THREAD

**Issue by cofiem** [inaturalist/SeekReactNative#545]
**Describe the bug**
There is no text for the notifications on the notifications page.

**To Reproduce**
1. Tap on the bell icon in lower right
2. When there are notifications, they have no text

**Expected behavior**
The notifications should have text, otherwise I have no idea what the notifications are for.

**Screenshots**
![Screenshot_20221204-091403](https://user-images.githubusercontent.com/441771/205466198-845fc002-68f0-4a31-9813-a4f0c6076eb7.png)

**Smartphone (please complete the following information):**
 - Device: Google pixel 3a
 - OS: Android 12
 - Version: 2.14.6 (266)

**Additional context**
n/a

**Comment by jtklein** [comment]
Hello and thank you for the bug report. I can not replicate this error on my Android device.
What language are you using in the app, and on your phone?

**Comment by cofiem** [comment]
Thanks for taking a look.
The app language is `[x] use device language settings` with ENGLISH in the green button.
The phone language is `English (Australia)`.

**Comment by jwidness** [comment]
Also reported here: https://forum.inaturalist.org/t/seek-notifications-list-shows-blank-notifications/24356

**Comment by cofiem** [comment]
If it helps, I'm seeing the same as that forum report - the list of notifications has no text, but the achievements page (and individual achievement pages) looks ok to me.

**Comment by jtklein** [comment]
@cofiem @jwidness Thanks for this report. I have been working on the notifications list and have replaced it with a new component. I could not replicate this bug on my Android device. So, therefore, I would be happy if someone can test that this bug is no longer appearing on the latest test version. You have to download the beta test version from the PlayStore in order to test, let me know if you need assistance in how to do that.

**Comment by cofiem** [comment]
I joined the beta program for the Seek app on the Google Store. Is this what you meant?

I then updated the app. It says version 2.14.7 (267) on the about page. Is this the beta version?
I also cleared the app cache.

Unfortunately, the notifications page looks the same - it still has no text.

**Comment by jtklein** [comment]
Thank you. Yes, you did the correct steps. Then, we have to look into it some more.

**Comment by cofiem** [comment]
@kueda Yes, when I turn dark mode off, I can see the text in the notifications! Bit of an odd one, but thanks for checking.
