### ISSUE TITLE
Species seen in Challenge only partially appear

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#564]
**Describe the bug**
If i have species in a current project, only part of the photo is shown on the project page. 

**To Reproduce**
1. Open up a project page in which you have at least one species. 
2. Only part of the species shows.
3. Tapping on that part of the species photos does take you to the species page. 

**Expected behavior**
I should see all of the species I've added to the challenge.

**Screenshots**

![image](https://user-images.githubusercontent.com/15896181/217402022-395ea1b5-4165-4261-8faa-d9b0df0062d1.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.2
 - Version: 2.14.7 (269)

**Additional context**
Add any other context about the problem here (i.e. what language are you using, do you have location settings turned on, did you have cell signal)

**Comment by jtklein** [comment]
Fixed in upcoming version.
