### ISSUE TITLE
Requesting password reset email doesn't generate any email

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#565]
**Describe the bug**
When requesting a password reset email, I'm told an email is sent but SendGrid shows no email generated.

**To Reproduce**
1. Make sure you're logged out of iNat, then go to log in page in Seek.
2. Tap on "Forgot your password?"
3. Enter the email address associated with your iNat account and tap on Reset My Password.
4. Seek tells you an email has been sent.
5. No email appears, and if you check SendGrid, no email has been generated. 

**Expected behavior**
A password reset email should be generated and sent.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.2
 - Version 2.14.7 (269)

**Additional context**
Add any other context about the problem here (i.e. what language are you using, do you have location settings turned on, did you have cell signal)

**Comment by jtklein** [comment]
This was fixed on the API side, nothing to do in the client here.
