### ISSUE TITLE
Both small_inception_tf1.tflite and optimized_model.tflite are included in release APKs

### ISSUE THREAD

**Issue by maxogden** [inaturalist/SeekReactNative#576]
In the `org.inaturalist.seek_2023-02-24.apk` (293MB) there are copies of both `small_inception_tf1.tflite` (the sample model) and `optimized_model.tflite` (the production model). From my limited understanding `small_inception_tf1.tflite` is not used, so it would save about 80MB on everyones phone if it was removed from builds

**Comment by jtklein** [comment]
Thank you @maxogden for this report. It was indeed true that this file was being included in the built apps. I have updated the build structure and README, so that this should be fixed with the next release.
