### ISSUE TITLE
Add common names in Dutch

### ISSUE THREAD

**Issue by albullington** [inaturalist/SeekReactNative#59]
We're able to add support for Dutch now that the Dutch translation is completed. This means also adding a new common names csv into Realm and having the app check for these localized names in the AR camera. 

Additionally, we'll need to update app store descriptions on iOS and Android with Dutch.

**Comment by albullington** [comment]
Added the new common names files into my local project. Now, just need to update the app store descriptions.

**Comment by albullington** [comment]
@abhasinat would you be able to create Dutch screenshots that I can pop into the Android and Apple stores? Ideally, I'd love your help running through the simulators / devices in Dutch, at least for the devices that you have on hand, so we can split up the work.

**Comment by abhasinat** [comment]
I'm happy to help you with this, but I think the only "correct" device size I have for screenshots is the Android– Samsung Galaxy S8. Let me know if I can be helpful at all. I'm happy to edit and add in the badges to the screenshots whenever.

Here's a link to the screenshots doc for reference: https://docs.google.com/document/d/1oValEpsF3yrpb2bPtHfcv9kMUbBpo2e4FDQwdvgO1DI/edit

**Comment by albullington** [comment]
Nice, if you can at least take the Android ones that would be a big help. You should be able to switch languages by going into the menu, as described here: https://videotron.tmtx.ca/en/topic/samsung_galaxys8/changing_the_keyboards_language.html#step=1

**Comment by abhasinat** [comment]
Can do. Will get these done by tomorrow.

**Comment by albullington** [comment]
@abhasinat all the iphone / ipad shots are ready in iNaturalist > screenshots > seekv2 > dutch.

**Comment by abhasinat** [comment]
Android screenshots have been added to iNaturalist > screenshots > seekv2 > android > dutch!
