### ISSUE TITLE
Add assets for June challenges

### ISSUE THREAD

**Issue by albullington** [inaturalist/SeekReactNative#62]
Update Realm and the assets library with the June challenge background images & badge images.

**Comment by albullington** [comment]
@abhasinat I added the challengedetails image and the placeholder badge image to v2.1.0, and I wanted to make sure that the homechallenge image for June was still on your radar since I couldn't find that in Google Drive.

**Comment by abhasinat** [comment]
I've reorganized the Google Drive and combined everything for Seek into one folder!

The updated June Badge is in iNaturalist/Design/Seek 2019 - React Native/Dev Assets/4_Profile/Badges, and I everything should be up to date in the Dev Assets folder.

**Comment by albullington** [comment]
Okay, having everything in one place is definitely helpful. However, I'm looking in iNaturalist/Design/Seek 2019 - React Native/Dev Assets/1_Home Screen/Onboarding, and I don't see img-homechallenge-june.

**Comment by abhasinat** [comment]
Aha, those were done but I just forgot to export them from Sketch. They should be on Drive now.
