### ISSUE TITLE
Camera improvements 

### ISSUE THREAD

**Issue by elesto** [inaturalist/SeekReactNative#622]
I am seeing much higher resolution and improved focus with the new camera module in v 2.15.0 

Phone Xperia 5 II

thanks!

**Comment by jtklein** [comment]
Thanks for your comment. We are seeing an increase in some native crashes with the new camera, is this something you are experiencing as well?

**Comment by elesto** [comment]
> Thanks for your comment. We are seeing an increase in some native crashes with the new camera, is this something you are experiencing as well?

None as of yet
