### ISSUE TITLE
inatjs requests send incorrect User-Agent header on Android

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#652]
**Describe the bug**
Requests that go through inaturalistjs on Android send a User-Agent header like `okhttp/4.9.2`. It should send a Seek-specific User-Agent as it does in iOS

**To Reproduce**
1. Open Seek and sign in to an iNat account
2. Return to the home screen to make sure announcements load (this may require a force-quit)
3. Go to Kibana and filter for requests by the signed in user. The `parsed_user_agent.original` field shows `okhttp/4.9.2`

**Expected behavior**
It should show a User-Agent with the word Seek in it, e.g. `Seek/2.16.0 Handset (Build 323) Android/14`

**Screenshots**
<img width="742" alt="Screenshot 2023-11-22 at 3 17 16 PM" src="https://github.com/inaturalist/SeekReactNative/assets/22691/656d22ac-7a6e-4b2d-b047-a338081c8be4">

Note that the first line is from Android and the second two are from iOS.

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: Android 13
 - Version: 2.16.0 (323)

**Additional context**

This might also be addressed in inaturalistjs, but I suspect part of the problem is specifying the user agent option as `user_agent: "something"` in JS rather than `"User-Agent": "something"`.

This is particularly important b/c without the correct user agent, the client-specific announcement targeting doesn't work, which means at present the only announcements we can show in Seek are ones that target all mobile clients.

Note that this seems to happen to regardless of authentication.

**Comment by jtklein** [comment]
Could not replicate this running on simulator/emulator in development mode today.
<img width="306" alt="Screenshot 2024-01-13 at 00 02 49" src="https://github.com/inaturalist/SeekReactNative/assets/17345891/b1aeaffa-ce5f-4b21-8fab-968b5112d33e">
