### ISSUE TITLE
Updating Text Styles in Seek

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#680]
Lato can be downloaded [here](https://www.latofonts.com/lato-free-fonts/).

### Text Style Updates

Banner Text:
- Lato Bold 18pt
- Letter spacing: 1px
- Line height: 22

Body Text & Body Text-White:
- Lato Regular 15pt
- Letter spacing: 0px
- Line height: 21

Button Text:
- Lato Bold 17pt
- Letter spacing: 1px
- Line height: 21

Challenge Description Text:
- Lato Medium 15pt
- Letter spacing: 0px
- Line height: 24
- Paragraph spacing: 0.1

Challenge Month:
- Lato Regular 17pt
- Letter spacing: .75px
- Line height: 21

Challenge Title:
- Lato Bold 22pt
- Letter spacing: 1px
- Line height: 27

Empty State:
- Lato Medium 18pt
- Letter spacing: 0px
- Line height: 24

Header:
- Lato Bold 18pt
- Letter spacing: 1px
- Line height: 22

Small Light Heading & Small Light Heading White:
- Lato Regular 13pt
- Letter spacing: .75px
- Line height: 16

Species Title:
- Lato Regular 29pt
- Letter spacing: 0px
- Line height: 35

Splash Text:
- Lato Medium 16pt
- Letter spacing: 0px
- Line height: 19

Text Highlight:
- Lato Bold 17pt
- Letter spacing: 1px
- Line height: 24

### Other font updates

Unfortunately, not all text in Seek is not covered by the above font styles. For all other text, please follow the below guidelines:

Font replacement is as follows:
- Whitney Light -> Lato Regular
- Whitney Book -> Lato Regular
- Whitney Medium -> Lato Medium
- Whitney Semibold -> Lato Bold

When replacing Whitney -> Lato for something without a text style, decrease the font size by 1pt and follow the above conversion. Letter spacing and colors remain the same, but line height does change depending on the size of the text- we can fix that in a feedback round.

**Comment by jtklein** [comment]
Released in 2.15.8
