### ISSUE TITLE
Open app straight into camera

### ISSUE THREAD

**Issue by verhovsky** [inaturalist/SeekReactNative#693]
Every time I open the app I have to wait for it to load and then immediately tap the camera icon. I have never opened Seek to do anything other than immediately open the Camera and pointing it at something.

Also there's constantly the warning after opening the app that I never read that I have to click out of. I think it gets reset either when I dont open the app for a while. Or maybe updating the app resets it? I've seen it more than 5 times. 1 time is already more than sufficient.

When I see an animal I have to take the phone out of my pocket, unlock it, close the current app, swipe to the page where Seek is, tap on Seek. All of this adds up to a seconds in which sometimes the animal flies away, so please remove these 2 extra taps I need to do before actually using the app.

**Comment by jtklein** [comment]
If you long press on the app icon on iOS and some Android phones there should be the option to jump directly to the "Seek Camera". This will open the app and immediately navigate to the camera.
For legal reasons, we can not not show the disclaimer first.

**Comment by verhovsky** [comment]
It does not. Just opens the regular start app screen. iOS 17.5.1, iphone 15 pro, seek 2.16.0

I personally have never used the tap and hold feature for any app and I'm not going to start but I guess you've answered the question.
