### ISSUE TITLE
iNaturalist view says "Log In With iNaturalist" even when I'm logged in

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#79]
To replicate, log in with your iNat account, then go to the iNaturalist view from the side menu. Even though you're logged in, there's still a button at the bottom that says "LOG IN WITH INATURALIST." IMO, that should be replaced with a notice that says "Signed in as USERNAME" or something so the user can confirm that they're signed in and know which account they used to sign in.

**Comment by albullington** [comment]
Updated to this, which gives users the option to sign out: https://zpl.io/anyBzjn
