### ISSUE TITLE
Add Terms of Service to Signup/Login Flow

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#85]
1. Create a new screen identical to the Privacy Policy titled "Terms of Service" with text pulled in from https://www.inaturalist.org/pages/terms.
![Signup-6-ToS-iPhone8@2x](https://user-images.githubusercontent.com/44380775/58674330-35f70600-8304-11e9-8b47-2c5dff74d9f9.png)
Zeplin link: zpl://screen?pid=5bd385bce9f15622d2ef10c2&sid=5cf02de96af3e11bb4564d02

2. Add a "Terms of Service" link to the above page directly next to the Privacy Policy link on the Birthday screen and the "Welcome to Seek" screen.
![Signup-5-LoginSuccess-iPhone8-ToSUPDATED@2x](https://user-images.githubusercontent.com/44380775/58674329-35f70600-8304-11e9-9e3f-ab7c1ad5cd60.png) ![Signup-7-SignupAgeVerification-dateentered-iPhone8-ToSUPDATED@2x](https://user-images.githubusercontent.com/44380775/58674331-35f70600-8304-11e9-9972-9d2ab88502be.png)
Zeplin links:
zpl://screen?sid=5cf02de978761e1b1b430f5b&pid=5bd385bce9f15622d2ef10c2
zpl://screen?pid=5bd385bce9f15622d2ef10c2&sid=5cf02deb617ba078b5e40fa6

Note: @kueda mentioned he needs to update the Terms of Service text and run it by Barb, so this text will need to be updated in Seek once it is updated on the web.

**Comment by albullington** [comment]
@abhasinat do we need to add the terms of service here too? https://zpl.io/VOxP138

I assumed that users would be able to navigate to the ToS screen wherever we currently have the privacy policy.

**Comment by abhasinat** [comment]
Yep, good catch! I'll whip up a design and put it on Zeplin.

**Comment by abhasinat** [comment]
Added here. I designed them on smaller screens to make sure they fit. Let me know if you have any questions!

Screen: https://zpl.io/29KqlXw
Error state: https://zpl.io/Vx6mKNE
