### ISSUE TITLE
Use metadata from imported photo to set observation's date and location.

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#91]
If I import a photo into Seek and it gets added to my observations, Seek uses the date and location from when/where I was when the photo was added to Seek, not the date or location from the photo's metadata. Is it possible to use the photo's metadata here?

**Comment by albullington** [comment]
I can double check on this, but the way the code should work now, it checks to see if the photo has metadata, and if it doesn’t, it defaults to the fuzzed user location. So I think the issue here is that some photos don’t have any metadata at all (like the ones taken through Seek).

Similarly, the code should be checking for a photo metadata timestamp before defaulting to the current date.

**Comment by albullington** [comment]
@tiwane okay I think this is halfway solved. I updated the Species Detail screen to show the date when the photo was taken, and the range map also shows the location where the photo is taken. 

The exception to this is photos taken by Seek, which don't have metadata for location. If that's an important feature, I think we'll need to make an issue in the [RN iNat Camera](https://github.com/inaturalist/react-native-inat-camera) repo for Alex.

**Comment by albullington** [comment]
@abhasinat this is the issue related to the range map

**Comment by tiwane** [comment]
In 2.2.0 (38) I imported [this photo](https://www.dropbox.com/s/btaqm82fiaxun78/DSC02937.jpg?dl=0). Seek got the date correct, but not the location.

![image](https://user-images.githubusercontent.com/15896181/59701484-97dfb880-91aa-11e9-8030-50eaace9b232.png)

**Comment by albullington** [comment]
Is this a consistent experience with all photos, or just this photo? Are you noticing it through photos taken through the iOS camera, Seek, or another camera?

**Comment by albullington** [comment]
Fixed - was accidentally overwriting the photo metadata with user location data in the gallery results screen.
