### ISSUE TITLE
Help text on the AR Camera changes based on taxonomic level

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#95]
Right now, the help text on the camera always says "Keep scanning the environment for organisms to identify!"

It should change based on taxonomic level:
**Kingdom, Phylum**: "Keep scanning the environment for organisms to identify!"
[https://zpl.io/adrQo85](url)

**Class, Order, Family**: "Try different angles till you can get the identification to species!"
[https://zpl.io/2pnNqZj](url)

**Genus**: "Almost at species!"
[https://zpl.io/25Gml3o](url)

**Species**: "That’s it! Now take a picture to add this species to your observations."
[https://zpl.io/2ZjOZvE](url)

**Comment by albullington** [comment]
Updated text in English and added updated strings to Crowdin.
